sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
addons:
  apt:
    packages:
    - libfftw3-dev
script:
    - nosetests

